# Generated by Django 4.2.1 on 2023-05-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='post',
            name='student',
        ),
    ]
