# Generated by Django 4.2.1 on 2023-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_delete_postsuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
