# Generated by Django 4.2.1 on 2023-05-12 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_postsuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsuser',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_manage', to=settings.AUTH_USER_MODEL),
        ),
    ]
