# Generated by Django 4.2.1 on 2023-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_view_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_pictures/'),
        ),
        migrations.AddField(
            model_name='post',
            name='mod',
            field=models.IntegerField(null=True),
        ),
    ]
