# Generated by Django 4.2.1 on 2023-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_student_major_alter_student_student_id_delete_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='final_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='middle_grade',
            field=models.FloatField(null=True),
        ),
    ]
