# Generated by Django 4.2.1 on 2023-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.IntegerField()),
                ('num', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('writer', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('view', models.IntegerField()),
            ],
        ),
    ]
