# Generated by Django 4.2.1 on 2023-06-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
