# Generated by Django 4.2.1 on 2023-05-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_alter_course_course_id_alter_takes_final_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.CharField(default='', max_length=15),
        ),
    ]
