# Generated by Django 4.2.1 on 2023-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_course_name_alter_course_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
